backend:
  image: allush/yii-app
  container_name: backend.penzaremeslo.production
  working_dir: /app
  entrypoint: ['./config/up.sh']
  volumes:
    - '../../backend:/app'
    - '../../php/config/production/php.ini:/usr/local/etc/php/conf.d/custom.ini'
  external_links:
    - 'mysql.allush.ihor.ru'
  links:
    - 'mail:mail.penzaremeslo.production'
  env_file:
    - ./config.env

http:
  container_name: http.penzaremeslo.production
  image: nginx
  ports: ['1082:80']
  links:
    - 'backend:backend.penzaremeslo.production'
  volumes:
    - '../../http/config/production:/etc/nginx/conf.d'
    - '../../backend:/app'

mail:
  image: onesysadmin/ubuntu-postfix
  container_name: mail.penzaremeslo.production